import type { Customer, Employee, Invoice, Payslip, TallySettings } from "@/lib/mvp-store"

const xmlEscape = (value: string | number) => String(value)
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;")
  .replaceAll("'", "&apos;")

const tallyDate = (value: string) => value.replaceAll("-", "").slice(0, 8)
const amount = (value: number) => (Math.round(value * 100) / 100).toFixed(2)
const cleanNumber = (value: number | undefined) => Number.isFinite(value) ? Math.max(0, Number(value)) : 0

function monthEnd(month: string) {
  const [year, monthNumber] = month.split("-").map(Number)
  if (!year || !monthNumber) return `${month}-01`
  return new Date(year, monthNumber, 0).toISOString().slice(0, 10)
}

function ledgerEntry(name: string, value: number) {
  const isDebit = value < 0
  return `<ALLLEDGERENTRIES.LIST>
<LEDGERNAME>${xmlEscape(name)}</LEDGERNAME>
<ISDEEMEDPOSITIVE>${isDebit ? "Yes" : "No"}</ISDEEMEDPOSITIVE>
<LEDGERFROMITEM>No</LEDGERFROMITEM>
<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
<ISPARTYLEDGER>No</ISPARTYLEDGER>
<AMOUNT>${amount(value)}</AMOUNT>
</ALLLEDGERENTRIES.LIST>`
}

function partyLedgerEntry(name: string, value: number) {
  return `<ALLLEDGERENTRIES.LIST>
<LEDGERNAME>${xmlEscape(name)}</LEDGERNAME>
<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
<LEDGERFROMITEM>No</LEDGERFROMITEM>
<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
<ISPARTYLEDGER>Yes</ISPARTYLEDGER>
<AMOUNT>${amount(-Math.abs(value))}</AMOUNT>
</ALLLEDGERENTRIES.LIST>`
}

function envelope(companyName: string, messages: string[]) {
  return `<?xml version="1.0" encoding="UTF-8"?>
<ENVELOPE>
<HEADER>
<VERSION>1</VERSION>
<TALLYREQUEST>Import</TALLYREQUEST>
<TYPE>Data</TYPE>
<ID>Vouchers</ID>
</HEADER>
<BODY>
<IMPORTDATA>
<REQUESTDESC>
<REPORTNAME>Vouchers</REPORTNAME>
<STATICVARIABLES><SVCURRENTCOMPANY>${xmlEscape(companyName)}</SVCURRENTCOMPANY></STATICVARIABLES>
</REQUESTDESC>
<REQUESTDATA>
${messages.join("\n")}
</REQUESTDATA>
</IMPORTDATA>
</BODY>
</ENVELOPE>`
}

function invoiceValues(invoice: Invoice) {
  const items = invoice.lineItems?.length ? invoice.lineItems : [{
    taxableAmount: cleanNumber(invoice.taxableAmount),
    cgstAmount: cleanNumber(invoice.cgstAmount),
    sgstAmount: cleanNumber(invoice.sgstAmount),
    igstAmount: cleanNumber(invoice.igstAmount),
  }]
  const taxable = items.reduce((total, item) => total + cleanNumber(item.taxableAmount), 0)
  const cgst = items.reduce((total, item) => total + cleanNumber(item.cgstAmount), 0)
  const sgst = items.reduce((total, item) => total + cleanNumber(item.sgstAmount), 0)
  const igst = items.reduce((total, item) => total + cleanNumber(item.igstAmount), 0)
  const calculated = taxable + cgst + sgst + igst
  const gross = cleanNumber(invoice.amount) || calculated
  return calculated > 0
    ? { taxable, cgst, sgst, igst, gross, roundOff: gross - calculated }
    : { taxable: gross, cgst: 0, sgst: 0, igst: 0, gross, roundOff: 0 }
}

export function createTallySalesXml({ companyName, invoices, customers, settings }: { companyName: string; invoices: Invoice[]; customers: Customer[]; settings: TallySettings }) {
  const messages = invoices.map((invoice) => {
    const customer = customers.find((item) => item.id === invoice.customerId)
      || customers.find((item) => item.companyName.trim().toLowerCase() === invoice.companyName.trim().toLowerCase())
    const partyLedger = customer?.tallyLedgerName?.trim() || customer?.companyName || invoice.companyName
    const values = invoiceValues(invoice)
    const ledgers = [
      partyLedgerEntry(partyLedger, values.gross),
      ledgerEntry(settings.salesLedger, values.taxable),
      values.cgst ? ledgerEntry(settings.cgstLedger, values.cgst) : "",
      values.sgst ? ledgerEntry(settings.sgstLedger, values.sgst) : "",
      values.igst ? ledgerEntry(settings.igstLedger, values.igst) : "",
      Math.abs(values.roundOff) >= 0.005 ? ledgerEntry(settings.roundOffLedger, values.roundOff) : "",
    ].filter(Boolean).join("\n")
    return `<TALLYMESSAGE xmlns:UDF="TallyUDF">
<VOUCHER VCHTYPE="Sales" ACTION="Create" OBJVIEW="Accounting Voucher View">
<DATE>${tallyDate(invoice.date)}</DATE>
<VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
<VOUCHERNUMBER>${xmlEscape(invoice.sourceNumber || invoice.number)}</VOUCHERNUMBER>
<PARTYLEDGERNAME>${xmlEscape(partyLedger)}</PARTYLEDGERNAME>
<BASICBASEPARTYNAME>${xmlEscape(partyLedger)}</BASICBASEPARTYNAME>
<PERSISTEDVIEW>Accounting Voucher View</PERSISTEDVIEW>
<ISINVOICE>Yes</ISINVOICE>
<NARRATION>${xmlEscape(`Invoice ${invoice.sourceNumber || invoice.number} generated by ChanaX`)}</NARRATION>
${ledgers}
</VOUCHER>
</TALLYMESSAGE>`
  })
  return envelope(companyName, messages)
}

function deductionLedger(label: string, settings: TallySettings) {
  const normalized = label.toLowerCase()
  if (normalized.includes("provident") || /(^|\W)pf(\W|$)/.test(normalized)) return settings.pfPayableLedger
  if (normalized.includes("esi")) return settings.esiPayableLedger
  if (normalized.includes("professional") || /(^|\W)pt(\W|$)/.test(normalized)) return settings.professionalTaxPayableLedger
  if (normalized.includes("tds") || normalized.includes("income tax")) return settings.tdsPayableLedger
  return settings.otherDeductionLedger
}

export function createTallyPayrollXml({ companyName, payslips, employees, settings }: { companyName: string; payslips: Payslip[]; employees: Employee[]; settings: TallySettings }) {
  const messages = payslips.map((payslip) => {
    const employee = employees.find((item) => item.id === payslip.employeeId)
    const employeeLedger = employee?.tallyLedgerName?.trim() || employee?.employeeName || payslip.employeeName
    const deductionTotals = new Map<string, number>()
    payslip.deductions.forEach((item) => {
      if (item.amount <= 0) return
      const ledger = deductionLedger(item.label, settings)
      deductionTotals.set(ledger, (deductionTotals.get(ledger) || 0) + item.amount)
    })
    const exportedDeductions = [...deductionTotals.values()].reduce((total, value) => total + value, 0)
    const exportedNetPay = payslip.grossPay - exportedDeductions
    const ledgers = [
      ledgerEntry(settings.salaryExpenseLedger, -Math.abs(payslip.grossPay)),
      ledgerEntry(employeeLedger, Math.abs(exportedNetPay)),
      ...[...deductionTotals.entries()].map(([ledger, value]) => ledgerEntry(ledger, Math.abs(value))),
    ].join("\n")
    return `<TALLYMESSAGE xmlns:UDF="TallyUDF">
<VOUCHER VCHTYPE="Journal" ACTION="Create" OBJVIEW="Accounting Voucher View">
<DATE>${tallyDate(payslip.paymentDate || monthEnd(payslip.month))}</DATE>
<VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
<VOUCHERNUMBER>${xmlEscape(`PAY-${payslip.month}-${payslip.employeeCode}`)}</VOUCHERNUMBER>
<PERSISTEDVIEW>Accounting Voucher View</PERSISTEDVIEW>
<NARRATION>${xmlEscape(`${payslip.employeeName} salary for ${payslip.month} generated by ChanaX`)}</NARRATION>
${ledgers}
</VOUCHER>
</TALLYMESSAGE>`
  })
  return envelope(companyName, messages)
}

export function downloadXml(xml: string, fileName: string) {
  const url = URL.createObjectURL(new Blob([xml], { type: "application/xml;charset=utf-8" }))
  const link = document.createElement("a")
  link.href = url
  link.download = fileName
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}
